### ISSUE TITLE
support cake

### ISSUE THREAD

**Issue by EternalOne11** [Darkhax-Minecraft/Better-Hunger#1]
Can you add support for cake and blocks like it from other mods such as pancakes from autumnity.

**Comment by Darkhax** [comment]
This would be a nice feature but unfortunately there is no way to actually do this. I would basically need to replace every block which had a similar feature to add support and that's not very feasible.

**Comment by EternalOne11** [comment]
https://www.curseforge.com/minecraft/mc-mods/overeat Its a mod I commissioned awhile back.
