### ISSUE TITLE
Is there something similar to Hunger Overhaul in 1.16.5?

### ISSUE THREAD

**Issue by grisha252** [Darkhax-Minecraft/Better-Hunger#5]
I was looking for something that could tweak the hunger mechanics similar to Hunger overhaul in 1.12.2.

I'm actually interested in making you get hungrier faster and for various foods to give you less hunger points.

thanks.

**Comment by Darkhax** [comment]
There are no features like that in this mod and I am not aware of any mods that provide an alternative. I am not interested in providing those types of features in this project.
